config/routes.rb
Rails.application.routes.draw do

	resources :users

	match 'auth/:provider/callback', to: 'sessions#create_fb', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'contact' => 'static_pages#contact'
  get 'index' => 'static_pages#index'

  root to: 'static_pages#home'

  namespace :api do
    resources :tutorials do
      resources :lessons
    end
  end

  resources :tutorials

end

app/views/layouts/_footer.html.erb
<!-- Footer partial -->
<footer>
  <div class="footer-copyright">
    <div class="container">
    © 2015 Copyright Text
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<!-- Navigation bar partial -->
<nav>
    <div class="nav-wrapper grey darken-4">
      <div class="row">
      <a href="/" id="title" class="brand-logo">eMusic Lessons</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user %>
        <li><span>Signed in as </span><span><%= current_user.first_name.titlecase %></span></li>
        <li><%= link_to "Sign out", signout_path %></li>
        <% else %>
        <li><%= link_to "Facebook Login", "/auth/facebook" %></li>
        <li><%= link_to "Email Login", "/login" %></li>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <% end %>
      </ul>
      <% if current_user %>
        <img id="profile" class="circle responsive-img right" src=<%= current_user.image %>>
      <% end %>

      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="emlApp">
<head>
  <title>ElectronicMusicLessons</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

    <header>
      <!-- Render navigation bar on all pages -->
      <%= render 'layouts/navigation' %>
    </header>
    

    <main role="main">

    <%= yield %>
        
    </main>


    <!-- Render footer on all pages -->
    <%= render 'layouts/footer' %>

  </body>
</html>